### PR TITLE
Unittests [Draft]

### PR DESCRIPTION
**Pull request by tenko**
I looked into how to set up automatic testing and found the LLVM project has a nice python based tool called [lit](https://pypi.org/project/lit/) and was thinking this was a good fit.

In addition the LLVM project uses a utility called FileCheck which is internal to LLVM and lives inside the code base.
This tool replaces the use of grep to check output, as this can be problematic due to difference in grep implementations.
Fortunately there is a replacement tool found on [PYPI](https://pypi.org/project/filecheck/).

To run inside the unittests folder (currently the setup has hard coded path)
> pip3 install --user lit
> pip3 install --user filecheck
> lit .
This gives the output (abbreviated): 
> Unresolved Tests (15):
>   Oberon :: codegen/array_index_overflow.mod
>   Oberon :: codegen/case_1.mod
>   Oberon :: codegen/const_boolean.mod
>   Oberon :: codegen/const_char.mod
>   Oberon :: codegen/loop_1.mod
>   Oberon :: codegen/loop_2.mod
>   Oberon :: parser/array_overflow_constant_expr.mod
>   Oberon :: parser/empty_module.mod
>   Oberon :: parser/empty_procedure.mod
>   Oberon :: parser/fail_on_extra_semicolon.mod
>   Oberon :: parser/if_with_trailing_end.mod
>   Oberon :: parser/procedure_missing_return.mod
>   Oberon :: parser/procedure_return_not_handled.mod
>   Oberon :: parser/text_after_module.mod
>   Oberon :: parser/unterminated_module.mod
> 
> Testing Time: 10.41s
>   Passed           : 18
>   Expectedly Failed:  1
>   Unresolved       : 15

The unresolved tests here are disabled with UNSUPPORTED and marks potential bugs/crash or
features currently unsupported.

Note the testing depends on the JIT pull request to simplify running tests.
I was also thinking we could possible include the printf definition in the global scope if we detect a debug build
or add a flag for it. That would clean up the tests a bit, by removing the printf definition.

If this is a way forward I can look into integrating this into the CMAKE infrastructure and pick up the current build folder and executable.

### CODE REVIEW

**Comment by zaskar9** [comment]
Thank you! This work is very helpful!

My recommendation for the `printf` issue would be to use the `Out` module provided by `liboberon` that has (rudimentary) functionality to print text to the console. I would prefer if the tests did not rely on proprietary extensions of the compiler as I am trying to make it more compliant with standard Oberon. 

Note that all of these proprietary extensions are disabled in the latest version of the codebase (but can be re-enabled using the `-f` flag, cf. `Makefile` for `liboberon` that uses proprietary functionality so that "normal" modules do not have to).

If testing could be integrated into a test build that can be invoked using `cmake` that would simplify testing greatly!

**Comment by tenko** [comment]
Excellent. 

I will look into convert the tests to use the standard Out module.

That way it is also simple to run the test suite against other Oberon compiler for comparison.
I was thinking the [OBNC](https://miasap.se/obnc/) is useful to test against as it seem to be faithful to the Oberon-07 language report dated 2016, which I guess is the main target here.

Also note that I had to do some manual edits to the liboberon Makefile in order to compile the code on the MSYS environment. 
This should probably be changed to CMAKE at some point i guess?

I can take a stab at the CMAKE integration of the unit tests also, but I am not to
familiar with this tool though.

**Comment by tenko** [comment]
Test now work with CMAKE on the MSYS2 platform.

`printf` is removed except for printing of hex values.
I was thinking we could follow OBNC Out module here which has an extension for that [Out](https://miasap.se/obnc/obncdoc/basic/Out.def.html)

Also there should be a way to suppress warning output from the compiler as this get into the test log otherwise.

**Comment by zaskar9** [comment]
You are correct that the current version of `Out.Mod` is not complete. My goal is to be able eventually to compile the "official" `Out.Mod` by providing wrappers for the more lower-level modules of the Oberon runtime, i.e., `Texts.Mod` and `Oberon.Mod`, which is also partially there. However, `oberon-lang` does currently not support all of the functionality required to compile `Out.Mod`. Until this gap is closed, a temporary work-around would be to add a procedure with the following signature that wraps `printf`

```
PROCEDURE Hex*(i: LONGINT);
```

Nevertheless, even then, `Out.Mod` would be far from complete as several other procedures are also missing. This module has been developed very much on-demand. 😉

**Comment by tenko** [comment]
Very good.

The `printf` can be replaced later and maybe use `putchar` where possible, as this gives smaller binaries when static linking.
`printf` is like 100k due to float support.

Note there are several versions of the Out modules.

The original Oberon-2 has this defined in the Oakwood guidelines and many compiler implements this.

Then there is Oberon System 3 or Native (Several versions here) which has this module [link](ttps://github.com/OberonSystem3/Release_2.3.7_Sources/blob/main/Out.Mod).

In later versions of the Oberon system, this module seems to be removed and replaced by Texts and procedures: WriteInt, WriteString etc.

I am guessing you are following Oberon System 3?

**Comment by tenko** [comment]
OK. Working for me now.

With `ninja test` or `make test` all tests are run.
Currently a lot of output due to some failing tests and the warnings.

If you go into the `cmake-build-release/test` folder and execute `lit codegen/array_1.mod`, the single selected test will run.
 `lit -a codegen/array_1.mod` will show all the output.

**Review by zaskar9 — APPROVED** [review]
Code looks fine! Thank you! Ideally, there should be some documentation on the project's Wiki how to setup and run the tests.

**Comment by tenko** [comment]
I added the needed tools with pip:

>  pip3 install --user lit
>  pip3 install --user filecheck

and added `~/.local/bin` to the path.

The tools are probably not common enough to be included as a separate package.
I checked ArchLinux and could not find any.
pip can also install to a folder in the build folder, but that could be fragile.

**Pull request merged**
