### PR TITLE
Add missing FLT, PACK and UNPK procedures and expand unittests.

### PR DESCRIPTION
**Pull request by tenko**
Added support for FLT, PACK and UNPK procedures.
Added unittests covering all procedures.

The behaviour is now chosen to be in line with OBNC regarding undefined behaviour
as LLVM follow the C/C++ language model. 
Project Oberon has one place where a negative LSL shift value is used. For most
CPU platforms this is undefined behaviour.

This should be ready for merging if you could take a quick look and tests.

NOTE : For the future I will create own branch for changes. I see it creates a bit of a mess without.

### CODE REVIEW

**Comment by zaskar9** [comment]
Hey, this is great work in terms of filling the gaps and making these built-in functions bullet-proof and conforming to other implementations! 🙏🏻 I really appreciate the work, especially as I cannot devote at lot of time to this project. Just let me know when you feel it's ready to merge. I've also added you as a contributor to the repository and maybe that means that you can merge the pull request yourself!

**Comment by tenko** [comment]
That is very nice of you to grant access, but it seems that I cannot merge this myself alone.
I will give you a message when it is ready.
Still in the process of doing some more checking against Project Oberon.

For the future I was thinking to use the Github CI solution, so that all pull request get automatic tested against a
defined number of platforms. This should not be too difficult to set up.

It could even be used to build downloadable releases when it detect a git tagged version and so on.

I will take a look at this when this pull request is merged.
Believe this will make it less time consuming to decide on merging pull requests.

**Review by zaskar9 — COMMENTED** [review]
I've compiled the code and ran the tests on macOS (clang, arm64). The test summary is as follows.
```
********************
Failed Tests (4):
  Oberon :: codegen/arithmetic_12.mod
  Oberon :: codegen/array_5.mod
  Oberon :: codegen/case_1.mod
  Oberon :: codegen/loop_2.mod

********************
Unexpectedly Passed Tests (9):
  Oberon :: codegen/arithmetic_10.mod
  Oberon :: codegen/arithmetic_11.mod
  Oberon :: codegen/arithmetic_15.mod
  Oberon :: codegen/arithmetic_3.mod
  Oberon :: codegen/arithmetic_5.mod
  Oberon :: codegen/arithmetic_6.mod
  Oberon :: codegen/arithmetic_9.mod
  Oberon :: codegen/array_6.mod
  Oberon :: codegen/procedure_4.mod


Testing Time: 0.28s
  Unsupported        :  2
  Passed             : 87
  Expectedly Failed  : 12
  Failed             :  4
  Unexpectedly Passed:  9
```
It seems like most of the newly added tests fail (expectedly). Is that the intended behavior?

**Comment by tenko** [comment]
Yes,

There are 5 tests which should fail according to behavior of OBNC/Native Oberon:

1. builtin_asr_2.mod : fail with negative shift value (literal only)
2. builtin_lsl_2.mod : fail with negative shift value (literal only)
3. builtin_rol_2.mod : fail with negative roll value (literal only)
4. builtin_ror_2.mod : fail with negative roll value (literal only)
5. builtin_short_2.mod : fail with constant literal value

Otherwise tests should pass, which it seems it does.

**Review by zaskar9 — APPROVED** [review]

**Pull request merged**
