### PR TITLE
Update  README.md 

### PR DESCRIPTION
**Pull request by tenko**
* Added CI status badges
* Added info on MSYS2 build
* Added link to documentation

I think this is all in good shape now, so that focus can change to more real coding.
This CI stuff seems easy on the surface, but it is very hard to figure out what is wrong when it fails.

### CODE REVIEW

**Review by zaskar9 — APPROVED** [review]

**Comment by tenko** [comment]
I see the link to the documentation is now broken.
Not sure what happen here?

**Comment by zaskar9** [comment]
🤷🏻‍♂️

**Comment by zaskar9** [comment]
This action was created by GitHub when I activated GitHub Pages for the project, not from something coming from another repo.

**Comment by tenko** [comment]
Ah. I see.

Probably a default action was created when this feature was activated in the Github interface.

I could not find the yml file running this action and did not understand where it came from.

I just re-ran the Docs CI action and now it is working fine again.

**Pull request merged**
