### PR TITLE
Update CMake to include liboberon runtime in preparation for CI

### PR DESCRIPTION
**Pull request by tenko**
- Build liboberon with CMake (note some warnings where fixed in order to compile cleanly)
- Reduce verbosity of unittests
- Add install target. Can be run with example 'cmake --install . --prefix out'.

### CODE REVIEW

**Comment by zaskar9** [comment]
Wow! That's very nice! I was able to build the entire compiler including liboberon with `cmake` and Unix Makefiles on macOS. I also tried the new install target and got the following output.
```
❯ cmake --install . --prefix out
-- Install configuration: ""
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/bin/oberon-lang
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/lib/liboberon.a
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/lib/liboberondyn.dylib
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/include/oberon-lang/Oberon.smb
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/include/oberon-lang/Reals.smb
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/include/oberon-lang/Texts.smb
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/include/oberon-lang/Out.smb
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/include/oberon-lang/Random.smb
-- Installing: /Users/michael/Code/Oberon/oberon-lang/build/out/include/oberon-lang/Math.smb
```
This all looks fine with the exception of the dynamic library that has a different name now. I don't think the compiler (in JIT mode) will find it under this name anymore and will always to the static library. Is that intended behavior?

By the way, as you might have noticed from the appearance, disappearance, and reappearance of the file `gitlab-ci.yml`, I have been experimenting with CI on my universities infrastructure, where I keep a shadow copy of the GitHub repository in our self-hosted GitLab instance.

In this context, I was wondering what runners you are planning to use for CI/CD? If you need me to set up something on one of my servers, let me know. Alternatively, I could move the `oberon-lang` project (with the associated implications) from my personal GitHub account to the organization account of my research group. There we have a certain quota of free GitHub-hosted runners that we could use.

**Comment by zaskar9** [comment]
There are two problems on Linux with the GCC toolchain (Ubuntu 22.04.02 LTS, GCC 11.4.0).
```
cc1: error: command-line option ‘-Woverloaded-virtual’ is valid for C++/ObjC++ but not for C [-Werror]
```
*Possible Solution*: distinguish between C and C++ flags?

```
~/oberon-lang/liboberon/runtime.c:47:6: error: no previous declaration for ‘rt_reals_convert’ [-Werror=missing-declarations]
   47 | void rt_reals_convert(float x, int32_t n, char* d) {
      |      ^~~~~~~~~~~~~~~~
```
*Solution*: add definition to `runtime.h`

**Comment by tenko** [comment]
Yes, I was also shocked it worked the first time i worked. Expected a lot of work
to get it up and running.
 
The problem with duplicate target names for static and shared library should now be fixed.
The static library must be built into a separate location due to otherwise there would be a
name collision on the MSVC platform where the import library and static library has the same
name and ending.

Added the missing declaration of  rt_reals_convert.

I was planning to use the Github Action solution which is free tier for project with open source
license. There is a limit on the runtime per job of 30 minutes I believe, which should not be a
problem. If it becomes a problem one can just add the needed Docker images to a cache to avoid
rebuilding these images every time.

I think this is a good solution as it integrate nicely with the Github dashboard. 

The Linux build settings should be working as I was able to debug this on my laptop with the
Act tool. I also have build settings for MSYS2 and MacOS, but these are not tested locally.
I will open a new pull request on this. The setup will run on pull requests and push event and
upload the install content. I believe the test run is visible in the log. Otherwise I will add a
upload of the output here.

**Comment by tenko** [comment]
1. Just a hunch. I see `CMAKE_CXX_STANDARD` is set in the top `CMakeList.txt`. Should `CMAKE_C_STANDARD` be set? Could this be related?
2. If the static and shared library has the same name it will be : `oberon.lib` and `oberon.dll`. But there will also be generated a import library for the `oberon.dll` named `oberon.lib` and these will collide if built into the same location.

CMake should perhaps be regarded as an antithesis to Oberon... It is messy and flawed, but works and if the alternative is the gnu autotools, it is actually good.

**Comment by tenko** [comment]
Also it could be a temporary work around to disable error generation for warning messages?:

```
set_property(TARGET  ${LIBOBERON_SHARED}  
   PROPERTY COMPILE_WARNING_AS_ERROR OFF
)

set_property(TARGET  ${LIBOBERON_STATIC}  
   PROPERTY COMPILE_WARNING_AS_ERROR OFF
)
```

**Comment by tenko** [comment]
I think the problem is that the construct `add_compile_options` used in the top `CMakeList.txt` does not differ
between languages and the flags will be used both by the C and C++ compiler. 
Maybe it should be `string(APPEND CMAKE_CXX_FLAGS "cxx_flags")` and `string(APPEND CMAKE_C_FLAGS " c_flags")`

**Comment by zaskar9** [comment]
I've added two minor tweaks directly on the code on the `master` branch of your fork (which I was surprised that I'm allowed to do so).

1. The problematic option will now only get added if the language is C++ and ignored if the language is C.
2. I renamed the two targets for the library from `oberon_static`/`oberon_shared` to `liboberon-static`/`liboberon-shared`.

Everything works for me now under macOS/clang and Ubuntu/GCC. If you can confirm that my tweaks didn't break anything for you, I think this pull request is ready to be merged! Thanks for this great initiative! I saw that you even extended the CMake "language" with a Oberon-specific functionality! 😎

**Comment by tenko** [comment]
Excellent. I can confirm this works as expected for me.

Next I will look at Github Actions.
Turn out I can run the jobs from Github CLI by demand from my own
branch. This means I can properly test this before make PR.

**Review by zaskar9 — APPROVED** [review]
All looks fine to me now!

**Pull request merged**
